default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude_types: [xml]
      - id: no-commit-to-branch
        args: [--branch=master, --branch=release, --branch=main]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        args: [--in-place, --max-line-length=100]
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [--line-length=100]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=100, --ignore=E203]
  - repo: local
    hooks:
      - id: commit-msg
        name: commit-msg-hook
        description: Check commit message format
        entry: python ./ci/local/custom_pre_commit_hooks/custom_pre_commit_hooks/commit_msg_hook.py
        language: python
        stages: [commit-msg]
