version: '3'
services:
  calculator.postgres:
    image: postgres:latest
    hostname: calculator.postgres
    container_name: calculator.postgres
    ports:
    - ${POSTGRES_PORT}:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
    env_file:
    - ./.env
  calculator.backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - ${APP_PORT}:8000
    env_file:
    - ./.env
  calculator.rabbitmq:
    image: rabbitmq:management
    hostname: calculator.rabbitmq
    container_name: calculator.rabbitmq
    ports:
    - ${RABBITMQ_SERVER_PORT}:5672
    - ${RABBITMQ_CLIENT_PORT}:15672
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    env_file:
    - ./.env
volumes:
  pgdata:
  rabbitmq-data:
