version: '3'

services:
  {{cookiecutter.service_name}}.zookeeper:
    image: #zookeeper_image_path
    hostname: {{cookiecutter.service_name}}.zookeeper
    container_name: {{cookiecutter.service_name}}.zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  {{cookiecutter.service_name}}.kafka:
    image: #kafka_image_path
    hostname: {{cookiecutter.service_name}}.kafka
    container_name: {{cookiecutter.service_name}}.kafka
    depends_on:
      - {{cookiecutter.service_name}}.zookeeper
    ports:
      - "${KAFKA_PORT}:9092"
      - "${KAFKA_PORT_INTERNAL}:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://localhost:29092,PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_NUM_PARTITIONS: 10
      KAFKA_ZOOKEEPER_CONNECT: {{cookiecutter.service_name}}.zookeeper:2181
    restart: on-failure

    kafka-ui:
      image: #kafka_ui_image_path
      hostname: {{cookiecutter.service_name}}.kafka-ui
      container_name: {{cookiecutter.service_name}}.kafka-ui
      depends_on:
        - {{cookiecutter.service_name}}.kafka
      ports:
        - "${KAFKA_UI_PORT}:8080"
      extra_hosts:
        - host.docker.internal:host-gateway
      restart: always
      environment:
        KAFKA_CLUSTERS_0_NAME: Local
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: host.docker.internal:9092
        KAFKA_CLUSTERS_0_ZOOKEEPER: host.docker.internal:2181
