version: '3'

services:
 {{cookiecutter.service_name}}. kafka:
    image: bitnami/kafka:latest
    container_name: {{cookiecutter.service_name}}.kafka
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:${KAFKA_CONTROLLER_PORT}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIRS=/tmp/logs
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT},INTERNAL://:${KAFKA_INTERNAL_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:${KAFKA_PORT},INTERNAL://kafka:${KAFKA_INTERNAL_PORT}
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk

  {{cookiecutter.service_name}}.kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: {{cookiecutter.service_name}}.kafka-ui
    ports:
      - "${KAFKA_UI_PORT}:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: {{cookiecutter.service_name}}.kafka:${KAFKA_INTERNAL_PORT}
    depends_on:
      - {{cookiecutter.service_name}}.kafka
