version: '3'

services:
  kafka:
    # Kafka как Controller без Zookeeper
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      # Разрешить соединение без шифрования (отключить в Проде)
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Идентификатор экземпляра брокера Kafka в кластере
      - KAFKA_CFG_NODE_ID=1
      # Список идентификаторов брокеров, которые могут участвовать в выборах контроллера в кластере Kafka
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      # Соответствие между слушателями и протоколами безопасности
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      # Какие слушатели будут использоваться контроллером в кластере
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Директория, где будут храниться лог-файлы данных (сообщений) для тем и партиций
      - KAFKA_CFG_LOG_DIRS=/tmp/logs
      # Роли, которые будет выполнять данный брокер в кластере
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # Сетевые интерфейсы и порты, на которых брокер будет слушать входящие подключения
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
      # Адреса и порты, по которым клиенты и другие брокеры могут получить доступ к данному брокеру
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,INTERNAL://kafka:9094
      # Идентификатор кластера
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8080:8080
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: lkorDA4qT6W1K_dk0LHvtg
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
    depends_on:
      - kafka
