version: '3'

services:
  {{cookiecutter.service_name}}.redis:
    image: valkey/valkey:latest
    hostname: {{cookiecutter.service_name}}.redis
    container_name: {{cookiecutter.service_name}}.redis
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    env_file:
      - ./.env

volumes:
  redis_data:
