version: '3'
services:
  bff.backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - ${APP_PORT}:8000
    env_file:
    - ./.env
  bff.rabbitmq:
    image: rabbitmq:management
    hostname: bff.rabbitmq
    container_name: bff.rabbitmq
    ports:
    - ${RABBITMQ_SERVER_PORT}:5672
    - ${RABBITMQ_CLIENT_PORT}:15672
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    env_file:
    - ./.env
volumes:
  rabbitmq-data:
