version: '3'

services:
  {{cookiecutter.service_name}}.redis:
    image: #redis_image_path
    hostname: {{cookiecutter.service_name}}.redis
    container_name: {{cookiecutter.service_name}}.redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    env_file:
      - ./.env

volumes:
  redis_data: